### ISSUE TITLE
Come up with a brand new tagline

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#65]
It's currently: "A Modern, Fast, Open Source Language" as seen in the home page's header.

However, you could argue that it's a bit generic. 

It would be great if we could come up with a new one that summarises the language in an exciting way!

**Comment by lw64** [comment]
My idea was "Vala, the language for the Linux Desktop"

A criticism is that it is not multi-platform enough though.

**Comment by nahuelwexd** [comment]
Precisely, I don't like “for the Linux Desktop” because you automatically limit the scope.

The current tagline is the one elementary used on developer.elementary.io

**Comment by JeysonFlores** [comment]
I like the idea of  `"the language for the Linux Desktop"` because even though Vala is a multipurpose language.... let's be honest, the only sector where Vala can be a thing is the Linux Desktop and it's for what Vala was originally created (Out of the box GTK integration, Out of the box DBus integration and many other design decisions that make Vala being what it is).

Otherwise, I like the current tagline as well :D

**Comment by pervoj** [comment]
And also the demo code on the home page is desktop app, so it will perfectly fit together.

**Comment by Suzie97** [comment]
I think the tagline should communicate the advantages of vala, and the community's (brand) philosophy, values and beliefs. Personally, I use Vala because of it's first class integration with GObject which makes it really simple to build GTK apps. Also, I get to copy a lot of code from other elementary projects ;) 

But others might have other thoughts about the language and why they use it. So I think right now we should focus on what the community thinks about the language in order to come up with one that best represents the community.

Feel free to share your own reasons for using the language.

**Comment by pervoj** [comment]
I started with Vala when I switched to Linux, the only language I knew was Java and I wanted to develop in GTK. Vala was the most similar language with GTK support to Java. (So basically Vala was the second language I started to learn.) And even though I'm now able to use Python or JS, Vala is still my first choice in terms of GTK apps. It has the best integration with GTK, it isn't hard to find some examples (usually other apps that had to solve the same problem) and it has friendly and helpful community (actually Vala community was the first community I got in touch with). Well, when I'm trying to figure out why I use Vala, it's hard to come up with reasons. So I'd end it like this: I use Vala, because I just like it.

**Comment by lw64** [comment]
About vala being multi-platform: all platforms except Linux are just a pain to develop for. For windows you need msys2, and for macos homebrew. Native compiling is not supported by Vala yet. And that is only for compiling on that platform, not developing.
So Vala actually is definitly not a language to start with on platforms other than linux (unix).

**Comment by kmwallio** [comment]
`Vala - Like C# without the NET`

`Vala - The easiest way to manage native code`

`Because we couldn't call it C++++` (or C#++)

`Vala - Introspection and Applications made easy`

**Comment by colinkiama** [comment]
> Vala - Like C# without the NET

Hehehe

**Comment by NisooJadhav** [comment]
Vala - Supercharged C# for Linux

**Comment by nahuelwexd** [comment]
Taking into account that I am already reading 2 texts that indicate that they use Vala for its integration with GTK and other GNOME technologies (3 counting mine), I throw my proposals for the tagline:

- A language for the GObject ecosystem
- A familiar way to develop applications
- Build native interfaces in a simple way

**Comment by pervoj** [comment]
I would vote for "A familiar way to develop applications". In other words, it actually says it's easy to learn, which will be true with the upcoming guides.

**Comment by kmwallio** [comment]
> I share my reasons for using Vala: mainly, I use it because I like it. It's a language I find comfortable both for its similarity to C# and its deep integration with GObject, and I find its C code generation too interesting, so I tend to use it to learn this other language as well.

I echo this sentiment and also like "A familiar way to develop applications".

Vala is approachable and easy to jump into. A lot of other languages kind of break the familiarity aspect.

**Comment by Suzie97** [comment]
I've been collecting all the ideas shared by the community over the past days and trying to summarise them into one sentence. This is what I've come up with:
**A Familiar and Compatible Language to Build Native Applications**

- Familiar because of the similarity of the syntax with Java and C#
- Compatible because it compiles to C and also supports a large number of C libraries
- Native because of the integration with GTK (GObject), and also it has been advertised as a fast language before.

**Comment by colinkiama** [comment]
I've had some complaints about the Linux tagline already :sweat_smile: 

I'm going to update the tagline to focus more on familiarity. That doesn''t mean that it's what we're going to stick with though. Feel free to suggest more ideas

**Comment by nahuelwexd** [comment]
Closing issue, since we already have new tagline
